version: '3.9'

services:
  app:
    build: .
    ports:
      - '8081:80'
    volumes:
      - ./configs/.env:/app/configs/.env

  mongo:
    image: mongo:7
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 5s

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./infrastructure/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--storage.tsdb.retention.time=15d'
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

volumes:
  mongodata:
