global:
  scrape_interval: 15s
  external_labels:
    monitor: "micro-service-monitor"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "app"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["app:80"]